baseurl         = "https://example.com"
title           = "Chaschper - Hugo. HTML. Gallery. Art"
theme           = [ "hugo-chaschper" ] # add "matomo" if you want matomo tracking
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
canonifyurls    = true
assetDir        = "static"

[author]
    name    = "Jens-Christian Fischer"
    nick    = "jcfischer"
    email   = "jens-christian@invisible.ch"
    avatar  = "/img/avatar.jpg"
    description = "Maker. Musician"

[params]
  title       = "Invisible"
  domain      = "invisible.ch"
  subtitle    = "Hugo. HTML. Gallery. Art"
  copyright   = "Â© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Portfolio and Blog for Chaschper"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""
  showSubcribe = true
  show_reading_time = true

  mainSections = ["musings", "music", "code", "art"]

  twitterName = "jcfischer"
  fbName = "JensChristianFischer"
  githubName = "jcfischer"
  linkedinName = "jenscfischer"
  keybaseName = "jcfischer"
  flickrName = "jcfischer"


  pageNotFoundTitle = "404 - Page not found"

  googleSiteVerification = "xyzGoogleVerificationCode"


[permalinks]
  posts = "/:year/:month/:slug/"

[[memu.main]]
  name = "Home"
  url = "/"
  weight = 999

[[menu.main]]
  name = "Musings"
  url = "/categories/musings"
  weight = 200

[[menu.main]]
  name = "Music"
  url = "/categories/music"
  weight = 100

[[menu.main]]
  name = "Code"
  url = "/categories/code"
  weight = 99

[[menu.main]]
  name = "Galleries"
  url = "/galleries"
  weight = 95

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90


# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.IndieWeb]
    Country = "Switzerland"
    City = "Zurich"
    webmention = "invisible.ch"

# Enable this section for Matomo analytics. You will need to install
# the "matomo" theme and enable it in the themes setting above

# [params.matomo]
#     url = "https://matomo.invisible.ch"
#     id = 1
#
# [params.matomo.track]
#     button = "Enable Analytics"
#     message = "Your visits will be logged."
# [params.matomo.block]
#     button = "Disable Analytics"
#     message = "Your visits will *not* be logged."
